<?xml version="1.0"?>

<robot name="scout_v2" 
    xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:arg name="urdf_extras" default="scout_v2_extras.urdf" />

    <!-- Variables -->
    <xacro:property name="M_PI" value="3.14159"/>

    <!-- Vehicle Geometries -->
    <xacro:property name="base_x_size" value="0.9250000" />
    <xacro:property name="base_y_size" value="0.380000" />
    <xacro:property name="base_z_size" value="0.210000" />

    <xacro:property name="wheelbase" value="0.498" />
    <xacro:property name="track" value="0.58306" />
    <xacro:property name="wheel_vertical_offset" value="-0.0702" />

    <xacro:property name="wheel_length" value="1.1653e-01" />
    <xacro:property name="wheel_radius" value="1.6459e-01" />

    <!-- For testing, hang the robot up in the air
    <link name="world" />
    <joint name="world_to_base_link" type="fixed">
        <origin xyz="0 0 0.5" rpy="0 0 0" />
        <parent link="world"/>
        <child link="base_link"/> 
    </joint> -->

    <!-- Base link -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://scout_description/meshes/base_link.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0.008" rpy="0 0 0" />
            <geometry>
                <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
            </geometry>
        </collision>
        <collision>
            <origin xyz="0 0 ${base_z_size/6}" rpy="0 0 0" />
            <geometry>
                <box size="${base_x_size/6} ${base_y_size*1.65} ${base_z_size/3}"/>
            </geometry>
        </collision>
    </link>

    <link name="inertial_link">
        <inertial>
            <mass value="50" />
            <origin xyz="0.0 0.0 0.0" />
            <inertia ixx="2.288641" ixy="0" ixz="0" iyy="5.103976" iyz="0" izz="3.431465" />
        </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="inertial_link" />
    </joint>

    <!-- Scout wheel macros -->
    <link name="front_right_wheel_link">
        <inertial>
            <mass value="8" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.1171" ixy="0" ixz="0" iyy="0.1361" iyz="0" izz="0.1171" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://scout_description/meshes/wheel_type1.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
            <contact>
                <ode>
                    <min_depth>0.001</min_depth>
                </ode>
            </contact>
        </collision>
    </link>

    <joint name="front_right_wheel" type="continuous">
        <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="3.14 0 0" />
        <parent link="base_link"/>
        <child link="front_right_wheel_link"/>
        <axis xyz="0 -1 0" rpy="0 0 0" />
    </joint>

    <link name="rear_left_wheel_link">
        <inertial>
            <mass value="8" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.1171" ixy="0" ixz="0" iyy="0.1361" iyz="0" izz="0.1171" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://scout_description/meshes/wheel_type1.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
            <contact>
                <ode>
                    <min_depth>0.001</min_depth>
                </ode>
            </contact>
        </collision>
    </link>
 
    <joint name="rear_left_wheel" type="continuous">
        <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="rear_left_wheel_link"/>
        <axis xyz="0 1 0" rpy="0 0 0" />
    </joint>
 
    <link name="front_left_wheel_link">
        <inertial>
            <mass value="8" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.1171" ixy="0" ixz="0" iyy="0.1361" iyz="0" izz="0.1171" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://scout_description/meshes/wheel_type1.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
            <contact>
                <ode>
                    <min_depth>0.001</min_depth>
                </ode>
            </contact>
        </collision>
    </link>

    <joint name="front_left_wheel" type="continuous">
        <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="front_left_wheel_link"/>
        <axis xyz="0 1 0" rpy="0 0 0" />
    </joint>

    <link name="rear_right_wheel_link">
        <inertial>
            <mass value="8" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.1171" ixy="0" ixz="0" iyy="0.1361" iyz="0" izz="0.1171" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://scout_description/meshes/wheel_type1.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
            <contact>
                <ode>
                     <min_depth>0.001</min_depth>
                </ode>
            </contact>
        </collision>
    </link>

    <joint name="rear_right_wheel" type="continuous">
        <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="3.14 0 0" />
        <parent link="base_link"/>
        <child link="rear_right_wheel_link"/>
        <axis xyz="0 -1 0" rpy="0 0 0" />
    </joint>

    <!-- Additional definitions -->
    <xacro:include filename="$(arg urdf_extras)" />
</robot>
